## 라이브러리 불러오기

 Google Colab에서는 별도의 라이브러리를 설치할 필요 없이 NumPy를 불러올 수 있습니다. 

In [5]:
import numpy as np
print(np.__version__)

1.19.5


Ndarray 객체가 실제로 생성되는지 확인합니다. 

In [6]:
temp = np.array([1, 2, 3])
print(type(temp))

<class 'numpy.ndarray'>


## Numpy 배열 생성 및 둘러보기

두 개의 개별적인 리스트를 만들어봅시다.

In [7]:
data1 = [1,2,3]
data1

[1, 2, 3]

In [8]:
data2= [1,1,2,2,3,4]
data2

[1, 1, 2, 2, 3, 4]

만들어진 리스트를 Np.Array를 통해 배열로 변환해봅시다. 

In [9]:
my_array1 = np.array(data1)
print(my_array1) #코드를 실행해보세요.
print(my_array1.shape) #코드를 실행해보세요.

[1 2 3]
(3,)


In [10]:
my_array2 = np.array(data2)
print(my_array2) #코드를 실행해보세요.
print(my_array2.shape) #코드를 실행해보세요.

[1 1 2 2 3 4]
(6,)


**Shape()**는 배열의 크기를 확인하는 함수입니다. 

In [11]:
my_array3 = np.array([3,6,9,12])
print(my_array3) #코드를 실행해보세요.
print(my_array3.shape) #코드를 실행해보세요.
print(my_array3.dtype) #코드를 실행해보세요.

[ 3  6  9 12]
(4,)
int64


리스트를 만들고 변환할 필요 없이 **NumPy 배열을 바로** 만들 수도 있습니다.

리스트를 꼭 하나씩 넣을 필요는 없습니다. 여러 개를 동시에 넣어봅시다. 

In [12]:
my_array4 = np.array([[2,4,6],[8,10,12],[14,16,18],[20,22,24]])
my_array4 #코드를 실행해보세요. 

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18],
       [20, 22, 24]])

다음은 My_Array4 객체와 My_Array5 객체에 Shape 메소드를 적용한 후의 결과입니다.

In [13]:
my_array4.shape 

(4, 3)

In [14]:
my_array5 = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
my_array5.shape

(2, 2, 2)

My_Array4 데이터는 2차원의 배열 데이터로 4 * 3의 크기를 가졌습니다.  
MY_Array5 데이터는 3차원의 배열 데이터로 2 * 2 * 2의 크기를 가집니다.

## Numpy 기본 함수들

### arange

기본함수 중 Range 함수와 비슷하며, 숫자를 하나만 입력할 때는 0부터 숫자의 크기만큼 1차원배열이 만들어집니다.

In [15]:
arrange_array = np.arange(5)
arrange_array

array([0, 1, 2, 3, 4])

Arrage() 함수 내에 숫자를 넣어볼까요?  
1부터 9미만까지 3단위로 배열을 생성해봅시다. 

In [16]:
arrange_array2 = np.arange(1, 9, 3)
arrange_array2

array([1, 4, 7])

### zeroes, ones

할당하는 사이즈의 배열에 0이나 1을 더욱 쉽게 입력합니다. 

In [17]:
zeros_array = np.zeros((3,2))
print(zeros_array) #코드를 실행해봅시다. 
print("Data Type is:", zeros_array.dtype) #코드를 실행해봅시다.  
print("Data Shape is:", zeros_array.shape) #코드를 실행해봅시다. 

[[0. 0.]
 [0. 0.]
 [0. 0.]]
Data Type is: float64
Data Shape is: (3, 2)


Np.Ones() 안에 Dtype='Int32' 형태로 입력하면, Int32 형을 강제로 지정합니다. 

In [18]:
ones_array = np.ones((3,4), dtype='int32')
print(ones_array) #코드를 실행해봅시다. 
print("Data Type is:", ones_array.dtype) #코드를 실행해봅시다. 
print("Data Shape is:", ones_array.shape) #코드를 실행해봅시다. 

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
Data Type is: int32
Data Shape is: (3, 4)


### reshape


Reshape는 배열의 차원 및 크기를 바꾼다는 의미입니다.

In [19]:
after_reshape = ones_array.reshape(6,2)
print(after_reshape) #코드를 실행해봅시다. 
print("Data Shape is:", after_reshape.shape) #코드를 실행해봅시다. 

[[1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]]
Data Shape is: (6, 2)


Reshape()를 사용해 배열을 변경할 때는 에러를 종종 경험합니다. 

In [20]:
after_reshape = ones_array.reshape(5,3)

ValueError: ignored

Reshape()는 Size가 동일한 상황에서만 변경이 가능합니다. 

이번에는 1차원에서 3차원으로 변경해보겠습니다. 

In [21]:
after_reshape = ones_array.reshape(2,3,2)
print(after_reshape)
print("Data Shape is:", after_reshape.shape)

[[[1 1]
  [1 1]
  [1 1]]

 [[1 1]
  [1 1]
  [1 1]]]
Data Shape is: (2, 3, 2)


이번에는 Reshape()에서 자주 사용되는 -1에 대해 알아봅시다.  
Reshape에서 -1은 다른 차원을 자동으로 계산합니다. 

In [22]:
after_reshape2= ones_array.reshape(-1,6)
print("reshape(-1,6)? \n")
print(after_reshape2)

reshape(-1,6)? 

[[1 1 1 1 1 1]
 [1 1 1 1 1 1]]


-1의 위치를 바꿔서, 실행해보았습니다. 

In [23]:
after_reshape3= ones_array.reshape(3,-1)
print("reshape(3, -1)? \n")
print(after_reshape3)
print("Data Shape is:", after_reshape3.shape)

reshape(3, -1)? 

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
Data Shape is: (3, 4)


-1을 고정한 채 3 대신 2,4와 같이 수정하며 Shape가 어떻게 변하는지 알아봅시다. 

## Numpy 인덱싱과 슬라이딩

특정한 데이터를 확인하는 것을 **인덱싱**이라고 하고, 데이터를 따로 추출해 내는 것을 **슬라이싱**이라고 합니다. 

In [24]:
my_array = np.arange(start=0, stop=4)
print(my_array) #코드를 실행해봅시다.

[0 1 2 3]


배열 인덱스는 위치 값이 0부터 시작합니다.  
인덱싱은 [] 안에 인자를 넣는 방식으로 합니다. 

In [25]:
print("my_array의 1번째 요소, 즉 위치값이 0인 것은: ", my_array[0])

my_array의 1번째 요소, 즉 위치값이 0인 것은:  0


In [26]:
print("my_array[0:3]:", my_array[0:3])

my_array[0:3]: [0 1 2]


Numpy 인덱싱에서는 마지막 값을 포함하지 않습니다.  
인자 앞에 -를 붙이면 뒤에서부터의 순서를 의미합니다. 

구구단 3단 숫자들이 모인 2차원 배열을 탐색해봅시다. 

In [27]:
my_array2 = np.arange(start=3,stop=30,step=3)
my_array2 = my_array2.reshape(3,3)
my_array2 #코드를 실행해봅시다.

array([[ 3,  6,  9],
       [12, 15, 18],
       [21, 24, 27]])

In [28]:
my_array2[0:2,0:2]

array([[ 3,  6],
       [12, 15]])

':' 기호 앞에 시작 인덱스를 생략하면 첫 번 째 위치 값인 0이 들어가고, 뒤에 인덱스를 생략하면 마지막 위치 값이 들어갑니다. 

In [29]:
my_array2[1:3,:]

array([[12, 15, 18],
       [21, 24, 27]])

둘 다 생략한 결과입니다. 

In [30]:
my_array2[:,:]

array([[ 3,  6,  9],
       [12, 15, 18],
       [21, 24, 27]])

## Numpy 정렬

### sort()

Np.**sort() 함수**는 원래의 배열은 그대로 놔둔 채 정렬의 결과를 복사본으로 반환합니다.  
Np.sort() 함수는 **오름차순**으로 자동 정렬됩니다.

In [31]:
height_arr = np.array([174, 165, 180, 182, 168])
sorted_height_arr = np.sort(height_arr)

print('Height Matrix: ', height_arr)
print('np.sort() Matrix: ', sorted_height_arr)

Height Matrix:  [174 165 180 182 168]
np.sort() Matrix:  [165 168 174 180 182]


np.sort() 를 통해 **내림차순**으로 정렬하고 싶을 때는 다음과 같이 하면 됩니다. 


In [32]:
desc_sorted_height_arr = np.sort(height_arr)[::-1]
print('np.sort()[::-1] : ', desc_sorted_height_arr)

np.sort()[::-1] :  [182 180 174 168 165]


### argsort()

Numpy. **Argsort()** 함수는 지정된 축을 따라 데이터 인덱스의 배열을 반환하도록 지정된 종류의 정렬을 사용해 입력 배열에서 간접 정렬을 수행합니다. 

In [33]:
fives = np.array([10, 5, 15, 20])
fives_order = fives.argsort()

print("The original data", fives)
print("The argsort(): ", fives_order)
print("The asending:", fives[fives_order])

The original data [10  5 15 20]
The argsort():  [1 0 2 3]
The asending: [ 5 10 15 20]


먼저 5의 배수들로 이루어진 Five 배열 객체를 만듭니다.  
Agsort()를 적용하지만 배열에는 결과가 없습니다.  
그러나 Fives_Order를 보면 오름차순으로 인덱스의 번호가 매겨진 것을 확인할 수 있습니다. 